import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'

const CONTENT_DIR = path.resolve('content')
const OUTPUT_FILE = path.resolve('src/data/posts.generated.js')

const formatDate = (value) => {
  if (value instanceof Date) {
    const y = value.getUTCFullYear()
    const m = String(value.getUTCMonth() + 1).padStart(2, '0')
    const d = String(value.getUTCDate()).padStart(2, '0')
    return `${y}.${m}.${d}`
  }

  if (typeof value === 'string') {
    const clean = value.trim()
    if (/^\d{4}-\d{2}-\d{2}$/.test(clean)) {
      const [y, m, d] = clean.split('-')
      return `${y}.${m}.${d}`
    }
    if (/^\d{4}-\d{2}-\d{2}T/.test(clean)) {
      const parsed = new Date(clean)
      if (!Number.isNaN(parsed)) {
        return formatDate(parsed)
      }
    }
  }

  return value
}

const files = fs.existsSync(CONTENT_DIR)
  ? fs.readdirSync(CONTENT_DIR).filter((file) => file.endsWith('.md'))
  : []

if (!files.length) {
  console.log('No markdown files found in /content. Add .md files and rerun.')
  process.exit(0)
}

const posts = files.map((file) => {
  const fullPath = path.join(CONTENT_DIR, file)
  const raw = fs.readFileSync(fullPath, 'utf8')
  const { data, content } = matter(raw)
  const { id, title, date, tags = [], category = 'posts', featured = false, excerpt = '' } = data

  if (!id || !title || !date) {
    throw new Error(`Missing required frontmatter (id, title, date) in ${file}`)
  }

  const safeDate = formatDate(date)

  return {
    id,
    title,
    date: safeDate,
    tags,
    category,
    featured,
    excerpt,
    content: content.trim(),
  }
})

const parseForSort = (value) => {
  const normalized = typeof value === 'string' ? value.replaceAll('.', '-') : value
  const stamped = typeof normalized === 'string' ? `${normalized}T00:00:00Z` : normalized
  const parsed = new Date(stamped)
  return Number.isNaN(parsed) ? 0 : parsed.getTime()
}

posts.sort((a, b) => parseForSort(b.date) - parseForSort(a.date))

const output = `// Auto-generated by npm run import-md. Do not edit manually.\n\nexport const posts = ${JSON.stringify(posts, null, 2)}\n\nexport default posts\n`

fs.writeFileSync(OUTPUT_FILE, output)
console.log(`Generated ${posts.length} posts -> ${path.relative(process.cwd(), OUTPUT_FILE)}`)
